"""initial_schema

Revision ID: 9e8669e0391b
Revises: 
Create Date: 2026-07-11 15:00:24.980315

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e8669e0391b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo_asociado', sa.Enum('INGRESO', 'SALIDA', 'AMBOS', name='tipoasociado'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entidad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo_cuenta', sa.Enum('AHORROS', 'CORRIENTE', 'TARJETA_CREDITO', 'INVERSION', name='tipocuenta'), nullable=False),
    sa.Column('saldo_actual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conector', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_generados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'SALIDA', name='tipomovimiento'), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuente', sa.Enum('MANUAL', 'IMPORTADO_CSV', 'BANCO_AUTOMATICO', name='fuentemovimiento'), nullable=False),
    sa.Column('hash_conciliacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuenta_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_bancarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_hash_conciliacion'), 'movimientos', ['hash_conciliacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_hash_conciliacion'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_table('reportes_generados')
    op.drop_table('cuentas_bancarias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
